pipeline {
    agent any
    tools {
        nodejs 'nodejs' // Debe coincidir con el nombre que pusiste en el paso 1
    }
    stages{
        stage('Build Frontend'){
            agent {
                docker { 
                    image 'node:20-alpine' 
                    args '-u root' // Necesario para instalar paquetes
                }
            }
            steps{
                sh 'apk add --no-cache libatomic'
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/benyax38/ToolRent-Tingeso.git']])
                dir("Frontend"){
                    sh "npm install" // Use 'bat' for Windows agents or 'sh' for Unix/Linux agents
                    sh "npm run build" // Use 'bat' for Windows agents or 'sh' for Unix/Linux agents
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("Frontend"){
                    script{
                        withDockerRegistry(credentialsId: 'dockerhub'){
                            sh "docker build -t benyax38/Frontend ."
                            sh "docker push benyax38/Frontend"
                        }
                    }
                }
            }
        }
    }
}