pipeline {
    agent any
    stages{
        stage('Build Frontend'){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/benyax38/ToolRent-Tingeso.git']])
                dir("Frontend"){
                    bat "npm install" // Use 'bat' for Windows agents or 'sh' for Unix/Linux agents
                    bat "npm run build" // Use 'bat' for Windows agents or 'sh' for Unix/Linux agents
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("Frontend"){
                    script{
                        withDockerRegistry(credentialsId: 'dockerhub'){
                            bat "docker build -t benyax38/Frontend ."
                            bat "docker push benyax38/Frontend"
                        }
                    }
                }
            }
        }
    }
}